### ISSUE TITLE
Grafana Datasource - fieldname translation?

### ISSUE THREAD

**Issue by TheAlchemistFLT** [wildmountainfarms/solarthing#215]
Hello again... looking at the Grafana dashboards it looks like the Grafana GraphQL datasource transposes the names of each of the datafields as stored in couchDB or published on the MQTT broker. Is there anywhere a list of the relevant datafields (I cant seem to find anywhere in Grafana to show the full list of valid fields (and also it wouldnt provide the mapping to couchdb etc.)

Being a newbie at this - I may of course just be being thick and missing something quite basic...

**Comment by retrodaredevil** [comment]
This has been a problem until recently when I released Wild GraphQL Data Source. Within the query editor, you should be able to view the documentation of the GraphQL API. I'll show you some screenshots of how to navigate it:

First, click the documentation button:

![image](https://github.com/wildmountainfarms/solarthing/assets/13205600/49a71a50-a3fd-47f6-a656-3c1f3feea889)

Within that, look for the root query:

![image](https://github.com/wildmountainfarms/solarthing/assets/13205600/cd71c3c5-7532-4506-a901-c9f59d5495e5)

Now you are here after clicking on "Query":

![image](https://github.com/wildmountainfarms/solarthing/assets/13205600/e1ffe626-6d70-4b54-820f-e37f1d9d1c4f)

Search for or scroll to `roverStatus`:

![image](https://github.com/wildmountainfarms/solarthing/assets/13205600/cbd283cd-56be-4379-ba1e-e99f29988b52)

Then click on PacketNode_RoverStatusPacket, then click on RoverStatusPacket and you should get here:

![image](https://github.com/wildmountainfarms/solarthing/assets/13205600/62cb2178-1a32-4e93-97dd-60b464d7d405)

From this, you have many different fields to choose from. For instance, if you wanted to graph the battery temperature Celsius and the controller temperature Celsius, you could do this:

```graphql
query ($from: Long!, $to: Long!) {
  data: queryStatus(
    from: $from
    to: $to
  ) {
    roverStatus {
      dateMillis
      packet {
        batteryTemperatureFahrenheit
        controllerTemperatureFahrenheit
        identityInfo {
          displayName
        }
      }
    }
  }
}
```

If you pay close enough attention to the documentation, you'll notice that `packet` corresponds with everything documented in RoverStatusPacket. I frequently will place my cursor inside that block and press CTRL+Space. That will bring up a list of things that can be autocompleted for.

Alternatively, you can also hover over something like "roverStatus" or "packet" and it should bring up a dialog that allows you to jump straight to the documentation of that thing.

There is definitely a lack of documentation, and I should probably create a more formal page describing what I just showed you here, so I appreciate the feedback. Additionally, I made a repo yesterday which I plan to maintain to house dashboards that anyone can use: https://github.com/wildmountainfarms/solarthing-dashboards/

**Comment by TheAlchemistFLT** [comment]
Thanks - very, very helpful.... and now I'm starting to get the hang of it... I've tweaked a few things and my own dashboard is starting to come together!
