### ISSUE TITLE
Is rpi zero w supported or is it just the rpi zero 2 W?

### ISSUE THREAD

**Issue by scully1707** [wildmountainfarms/solarthing#216]
Get this error message when trying to install on rpi zero w.  

root@DietPi:~# docker pull ghcr.io/wildmountainfarms/solarthing:latest
latest: Pulling from wildmountainfarms/solarthing
no matching manifest for linux/arm/v6 in the manifest list entries

**Comment by retrodaredevil** [comment]
The Raspberry Pi Zero is not officially supported. 

I believe it's possible to get a native install to work on a Raspberry Pi 0, you just need to get a Java 11 version installed on it which is easiest to do via SDKMAN. 

To be honest, I would **not** recommend trying to get it to work. A Raspberry Pi 0 is under powered and will take a bit for SolarThing to start up on.
