### ISSUE TITLE
pvoutput deprecated addbatchoutput

### ISSUE THREAD

**Issue by jwillemsen** [wildmountainfarms/solarthing#37]
I found recently that pvoutput has deprecated the addbatchoutput API, batching is now part of addoutput, but batching is only available for donations mode, see https://github.com/jwillemsen/saj_collector/issues/34. It looks this project needs to be updated because it uses addbatchoutput for example at https://github.com/wildmountainfarms/solarthing/blob/29e4c4f8058e6ac2bca05c3ee995b4a102a9c803/serviceapi/src/main/java/me/retrodaredevil/solarthing/pvoutput/service/PVOutputService.java

**Comment by retrodaredevil** [comment]
Thanks for letting me know. I like the change they made to make `addoutput` multipurpose, but really dislike non-donators cannot do batch uploads now. 

I guess I'll have to add an option to upload data one day at a time.
