### ISSUE TITLE
minor typo in readthedocs

### ISSUE THREAD

**Issue by bpehrson** [wildmountainfarms/solarthing#53]
There is a minor typo on page  https://solarthing.readthedocs.io/en/latest/data/graphql-grafana.html
In section "Installing and starting systemd service"
Says
sudo /opt/solarthing/other/system/install.sh graphql
should say 
sudo /opt/solarthing/other/systemd/install.sh graphql

**Comment by retrodaredevil** [comment]
Thanks for pointing that out. I should have fixed all the places where I made that mistake.
